export const LoanStatusColor = {
  50: "info",
  200: "info",
  100: "warning",
  300: "success",
  500: "error",
  600: "error",
  601: "error",
  "Loan Disbursal Failed": "error",
  true: "success",
  false: "status-deleted",
  Active: "success",
  "loanStatusType.closed.written.off": "error",
  "charges.StatusType.active.true": "success",
  "loanStatusType.failed": "error",
  "loanStatusType.submitted.and.pending.approval": "info",
  "loanStatusType.approved": "info",
  "loanStatusType.active": "success",
  "loanStatusType.overpaid": "info",
  "savingsAccountStatusType.submitted.and.pending.approval": "warning",
  "savingsAccountStatusType.approved": "info",
  "savingsAccountStatusType.active": "success",
  "savingsAccountStatusType.activeInactive": "success",
  "savingsAccountStatusType.activeDormant": "success",
  "savingsAccountStatusType.matured": "warning",
  "shareAccountStatusType.submitted.and.pending.approval": "warning",
  "shareAccountStatusType.approved": "info",
  "shareAccountStatusType.active": "success",
  "shareAccountStatusType.rejected": "status-rejected",
  "loanProduct.active": "success",
  "loanProduct.inActive": "error",
  "clientStatusType.pending": "warning",
  "clientStatusType.closed": "status-closed",
  "clientStatusType.rejected": "status-rejected", // write
  "clientStatusType.withdraw": "status-withdraw", // write
  "clientStatusType.active": "success",
  "clientStatusType.submitted.and.pending.approval": "warning",
  "clientStatusTYpe.approved": "info",
  "clientStatusType.transfer.in.progress": "warning", // write
  "clientStatusType.transfer.on.hold": "warning", // write
  "groupingStatusType.active": "success",
  "groupingStatusType.pending": "warning",
  "groupingStatusType.submitted.and.pending.approval": "warning",
  "groupingStatusType.approved": "info",
  "smsCampaignStatus.active": "success",
  "smsCampaignStatus.pending": "warning",
  "smsCampaignStatus.closed": "status-closed",
  "purchasedSharesStatusType.applied": "warning",
  "loanStatusType.sales.submitted.and.pending.approval": "secondary",
};
